### ISSUE TITLE
Setup a RelWithDebugInfo in SDK Project Demo

### ISSUE THREAD

**Issue by stonier** [stonier/win_ros#47]
Setup a configuration mode that will build .pdb files with release optimisations.

Also delete the debug configuration mode so there is no confusion.

**Comment by stonier** [comment]
What flags did you set here huey? Let me know here then close this issue. I'll update the roswiki.

**Comment by hughie** [comment]
I made ReleaseWithDebugInfo and deleted Debug. The difference between ReleaseWithDebugInfo(Off) and Release(On) is only optimization option. If you do debugging with optimization, then It's difficult to stop on breakpoint.
