### ISSUE TITLE
Cmake doesn't refer common_msgs stack while configuring custom stack

### ISSUE THREAD

**Issue by yichoe** [stonier/win_ros#73]
I created custom message stack and package. And I defined a message which has a member declared geometry_msgs/PoseStamped type. Although I include 'common_msgs' as calling 'find_package' and 'generate_messages' in CMakeList.txt, cmake says "Cannot locate message [PostStamped]: unknown package [geometry_msgs] on search path [...]".

I found there was no common_msgs directory in search path [...]. I think cmake's 'find_package' method ignores common_msgs stack while configuring custom stack in spite of including common_msgs.

**Comment by bit-pirate** [comment]
I'm no winros expert, but I think, you should include geometry_msgs, not common_msgs

**Comment by bit-pirate** [comment]
That did the trick.

**Comment by yichoe** [comment]
Built successfully. Thanks alot.
