### ISSUE TITLE
yujinrobot catkin missing

### ISSUE THREAD

**Issue by btshrewsbury** [stonier/win_ros#82]
Looks like some stuff got updated over at yujinrobot. The catkin.rosintall is pointing to https://github.com/yujinrobot/catkin.git (no longer exists), but it looks like you've moved to yujin_tools?

**Comment by stonier** [comment]
Ah...this win_ros repo was left around for fuerte. Are you trying to build on fuerte? 

I reorganised repos when I hit groovy as it was getting hard to track which forked repo was valid or not in yujinrobot. But it looks like I may have erred in not keeping a couple of those forks. 

The new repose are in https://github.com/ros-windows, with instructions for groovy on the [ros wiki](http://ros.org/wiki/win_ros). I'd recommend moving to groovy asap where the catkin api (and all of your cmake) will be relatively stable from here on. The sdk build is now working in the same way as fuerte with some upgraded build tools. Right now, I've got a colleague going through it checking and testing it before I officially make an announcement, but its usable. 

If you still are on fuerte and want to continue using fuerte, let me know.

**Comment by btshrewsbury** [comment]
Thanks for the quick update, Fuerte had install instructions so I went that route. I'll switch over to groovy, though the install instructions for Groovy seem to be either missing or hidden. If I run into any troubles I'll pass them along.

**Comment by stonier** [comment]
Just the Build SDK and Overlay instructions for Msvc at the moment. We're slowly updating the others, but essentially everything is working, including the MS express projects.

Jumping to groovy will mean also you don't need to make a radical update to all of your cmake again. Fuerte to groovy was a big jump, but it should be relatively stable from here on in.
